### ISSUE TITLE
Can't deserialize object inheriting from scipy.sparse.linalg.LinearOperator

### ISSUE THREAD

**Issue by phildb** [ipython/ipyparallel#168]
I stumbled upon this issue when trying to do batch optimization using a simple apply_async. Serializing/deserializing the optimization result dictionary leads to lock-ups if I use the L-BFGS-B because of the LbfgsInvHessProduct object contained in the output dictionary.

Simplest way to reproduce.

```python
from ipyparallel import Client
w = Client()
dv = w.direct_view()

with dv.sync_imports():
    from scipy import optimize

f = lambda x: (x - 1.0)**2
```
This will work:
```python
foo = dv.apply(lambda x: optimize.minimize(x, [0.0], method='Nelder-Mead'), f)
foo.result()
```

```
  final_simplex: (array([[ 1.       ],
       [ 0.9999375]]), array([  7.88860905e-31,   3.90625000e-09]))
           fun: 7.8886090522101181e-31
       message: 'Optimization terminated successfully.'
          nfev: 50
           nit: 25
        status: 0
       success: True
             x: array([ 1.])
```
This will not and will freeze on `foo.result()`:
```python
foo = dv.apply(lambda x: optimize.minimize(x, [0.0], method='L-BFGS-B'), f)
foo.result()
```

From calling `minimize` locally using `optimize.minimize(f, [0.0], method='L-BFGS-B')` we know the output should look like

```
 fun: array([ 0.])
 hess_inv: <1x1 LbfgsInvHessProduct with dtype=float64>
      jac: array([  9.99999988e-09])
  message: 'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
     nfev: 4
      nit: 1
   status: 0
  success: True
        x: array([ 1.])
```
The infringing object resides in hess_inv of the `optimize.minimize` output dictionary.

Strangely enough, I can pickle and unpickle it without any issue

```python
import cPickle
bar = optimize.minimize(f, [0.0], method='L-BFGS-B')
bar = bar['hess_inv']

cPickle.loads(cPickle.dumps(bar))
```
```
<1x1 LbfgsInvHessProduct with dtype=float64>
```

But I can't serialize/deserialize 
```python
from ipyparallel import serialize_object, deserialize_object

deserialize_object(serialize_object(bar))
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-be4d808c9513> in <module>()
----> 1 deserialize_object(serialize_object(bar))

/Users/philippe/anaconda/lib/python2.7/site-packages/ipyparallel/serialize/serialize.pyc in deserialize_object(buffers, g)
    130     bufs = list(buffers)
    131     pobj = buffer_to_bytes_py2(bufs.pop(0))
--> 132     canned = pickle.loads(pobj)
    133     if istype(canned, sequence_types) and len(canned) < MAX_ITEMS:
    134         for c in canned:

/Users/philippe/anaconda/lib/python2.7/site-packages/scipy/sparse/linalg/interface.pyc in __new__(cls, *args, **kwargs)
    140                                 " at least one of _matvec and _matmat.")
    141 
--> 142             obj.__init__(*args, **kwargs)
    143             return obj
    144 

TypeError: __init__() takes exactly 3 arguments (1 given)
```

Prior versions of ipyparallel were giving me the above error directly, but now `result()` locks-up instead. Using dill or cloudpickle doesn't work either.

I can get around the bug by replacing the LbfgsInvHessProduct object, which inherits from scipy.sparse.linalg.LinearOperator, by its dense representation using its `todense()` method, or by removing the 'hess_inv' item completely from the optimization output prior to serialization, or simply by using another algorithm which avoids the LbfgsInvHessProduct object altogether, e.g. Nelder-Mead or BFGS.

**Comment by minrk** [comment]
It's definitely a bug that `.result()` hangs instead of raises. I imagine this has to do with the deserialization failing in the new IO thread.

It does look like an issue with pickling the result, though. It fails with that error when I do it all locally:

```python
import pickle
from scipy import optimize

f = lambda x: (x - 1.0)**2
result = optimize.minimize(f, [0.0], method='L-BFGS-B')

pickle.loads(pickle.dumps(result))
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-b95d5325e4fe> in <module>()
----> 1 pickle.loads(pickle.dumps(result))

/Users/benjaminrk/conda/lib/python3.5/site-packages/scipy/sparse/linalg/interface.py in __new__(cls, *args, **kwargs)
    140                                 " at least one of _matvec and _matmat.")
    141 
--> 142             obj.__init__(*args, **kwargs)
    143             return obj
    144 

TypeError: __init__() missing 2 required positional arguments: 'sk' and 'yk'
```

**Comment by phildb** [comment]
```python
import pickle
from scipy import optimize

f = lambda x: (x - 1.0)**2
result = optimize.minimize(f, [0.0], method='L-BFGS-B')

pickle.loads(pickle.dumps(result))
```

works for me locally. I suppose it's a python 3.5 vs 2.7 difference.

It looks like instances of LbfgsInvHessProduct(LinearOperator) take a function as argument. Could this be a closure problem?

**Comment by minrk** [comment]
If it were a closure problem, it should fail on dumps, not loads. It appears to be a problem in how the object defines how it interacts with the pickle protocol, which may have changed in Python 3.

**Comment by phildb** [comment]
You're right, this is scipy bug, [#5894](https://github.com/scipy/scipy/pull/5894) to be precise, and the fix is now included in scipy 0.18. The code I've posted above now works with python 2.7.
