### ISSUE TITLE
Clusters tab

### ISSUE THREAD

**Issue by hannorein** [ipython/ipyparallel#15]
I'm confused as to how to enable the clusters tab in the latest development version

Is the syntax 
    
    c.NotebookApp.jupyter_server_extensions.append('ipyparallel.nbextension')

as per https://github.com/ipython/ipyparallel/blob/master/README.md or 

    c.NotebookApp.server_extensions.append('ipyparallel.nbextension')

as suggested in #11?

Neither of the options works for me. I just get the link to the repository. I also can't find any hint in the debug messages as to what is going on. Is this a bug or am I missing something?

    $ipython notebook --debug
    [D 17:26:44.196 NotebookApp] Config changed:
    [D 17:26:44.196 NotebookApp] {'NotebookApp': {'log_level': 10}}
    ...
    [D 17:26:44.199 NotebookApp] Loaded config file: /Users/rein/.jupyter/jupyter_notebook_config.py
    [D 17:26:44.200 NotebookApp] Config changed:
    [D 17:26:44.200 NotebookApp] {'NotebookApp': {'open_browser': False, 'server_extensions': ['ipyparallel.nbextension'], 'log_level': 10, 'ip': '*', 'certfile': u'/Users/rein/git/rebound/mycert.pem', 'password': u'sha1:****:*****', 'port': 9999}}
    [D 17:26:44.200 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /Users/rein/ipython
    [D 17:26:44.200 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /Users/rein/ipython
    [D 17:26:44.226 NotebookApp] Found kernel python2 in /Users/rein/Library/Jupyter/kernels
    [I 17:26:44.244 NotebookApp] Serving notebooks from local directory: /Users/rein/ipython
    [I 17:26:44.244 NotebookApp] 0 active kernels 
    [I 17:26:44.244 NotebookApp] The IPython Notebook is running at: https://[all ip addresses on your system]:9999/
    [I 17:26:44.244 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

**Comment by minrk** [comment]
`server_extensions` is correct, the readme is wrong. Beyond that, something has broken the extension, and I've been meaning to figure out what went wrong. I'll work on figuring it out now.

**Comment by hannorein** [comment]
Thanks. I'm glad it's not just me. I looked at the code base but couldn't figure our what is (not) happening.

**Comment by hannorein** [comment]
#16 works for me! Thanks again.

**Comment by minrk** [comment]
@hannorein thanks for testing!

**Comment by rohit-gupta** [comment]
Would anyone happen to know how to make this work on windows and Python2.7 ? It runs into os.symlink() in "install_nbextension". 

>symlink C:\Users\rohit_gupta\AppData\Roaming\jupyter\nbextensions\ipyparallel -> C:\Python27\lib\site-packages\ipyparallel\nbextension\static
>[W 00:38:41.710 NotebookApp] Error loading server extension ipyparallel.nbextension
>    Traceback (most recent call last):
>      File "C:\Python27\lib\site-packages\notebook\notebookapp.py", line 992, in init_server_extensions
>        func(self)
>      File "C:\Python27\lib\site-packages\ipyparallel\nbextension\handlers.py", line 72, in load_jupyter_server_extension
>        install_nbextension(static, destination='ipyparallel', symlink=True, user=True)
>      File "C:\Python27\lib\site-packages\notebook\nbextensions.py", line 200, in install_nbextension
>        os.symlink(path, full_dest)
>    AttributeError: 'module' object has no attribute 'symlink'
